### ISSUE TITLE
undefined var in gulpfile

### ISSUE THREAD

**Issue by gangstaJS** [MailOnline/VPAIDFLASHClient#5]
undefined var in gulpfile http://screenshot.su/show.php?img=a67972439d20ed11c606040d840d0197.jpg  / How fix it?

**Comment by Fetz** [comment]
Are you using Windows? if yes try to change the var in this line to point to the exe of flex sdk instead
https://github.com/MailOnline/VPAIDFLASHClient/blob/master/gulpfile.js#L25

if doesn't work then try to  console.log the argument `filePath` in line:
https://github.com/MailOnline/VPAIDFLASHClient/blob/master/gulpfile.js#L97

**Comment by gangstaJS** [comment]
I tried to enter the path directly 
```javascript

{
                    templateData: {
                        fileOutput: function (filePath) {

                            return files[0].fileOutputPath;

                            // return _.find(files, function(file) {
                            //     return filePath.indexOf(file.path) > -1;
                            // }).fileOutputPath;
                        },
                        mxmlc: flexSDK,
                        srcPath: flashSrcPath,
                        flashVersion: '10.1.0'
                    }
                }

```

then compiler output

**Comment by Fetz** [comment]
Try this:
`./vendor/bin/mxmlc.exe -output ./bin/VPAIDFlash.swf D:\projects\VPAIDFLASHClient\flash\src\com\dailymail\vpaid\VPAIDFlash.as -source-path flash/src -target-player=10.1.0`

If doesn't work try... I got issues with flexsdk not supporting 64 bit, so maybe that is the issue:
`java.home=C:/Program Files (x86)/Java/jre6`

If still is a no, try to check a newer version of flexsdk (you will probably will need to change the `-target-player` to a newer version)

**Comment by Fetz** [comment]
If you still have issue please open again
