### ISSUE TITLE
Support for ad volume

### ISSUE THREAD

**Issue by BranoMatan** [MailOnline/VPAIDFLASHClient#6]
I am autoplaying flash ads and I put the ads on mute.
My problem is that some of the ads are playing sounds, even when getAdVolume return 0 and the flash player sound indication is on mute. I want to to have an indication for that.
Is it possible to check the getAdVolume function, or to add mute data member and an indication for adMuted/adUnmuted?

**Comment by BranoMatan** [comment]
I have fixed the issue by editing your VPAIDFlash.as and compiling it into a new VPAIDFlash.swf.
Thanks anyway

**Comment by kailashju78** [comment]
Hi can i get VPAIDFlash.swf i am running with same issue, i need ad to be  loaded in muted state and on roll over un mute . is it possible?

**Comment by Fetz** [comment]
Some ads don't follow the spect that is why sometimes even if we say that is muted, and is not. I can try to change by changing the volume of the Stage itself not relying on the ad following or implementing the volume/muting.

Maybe was what @BranoMatan did in is case.

I will try in the weekend to implement this, I think I can do this (by doing a quick search) using the SoundMixer:

```
SoundMixer.soundTransform = new SoundTransform(0);
SoundMixer.soundTransform = new SoundTransform(1);
```

**Comment by kailashju78** [comment]
ok i will wait for your solution. Thanks for your reply.

**Comment by Fetz** [comment]
Was added in both VPAIDFlashClient project and in video-vast-vpaid

**Comment by BranoMatan** [comment]
@Fetz  Thanks a lot! 
I fixed the issue by also using SoundMixer, now I can use the original one :)
