### ISSUE TITLE
adap.tv VPAID tag

### ISSUE THREAD

**Issue by yairneumann11** [MailOnline/VPAIDFLASHClient#8]
I was trying to use the player to play the following tag:
http://ads.adaptv.advertising.com/a/h/XUUFc52Hk6Fg01bMBS16Tqn_qngdDNKLCE+L94vK1JQ=?cb=[CACHE_BREAKER]&pageUrl=http%3A%2F%2Ftest.com&description=VIDEO_DESCRIPTION&duration=VIDEO_DURATION&id=VIDEO_ID&keywords=VIDEO_KEYWORDS&title=VIDEO_TITLE&url=VIDEO_URL&eov=eov

this is a demo XML tag that should play on each try.

I took the demo files and changed the adURL var and made sure all the dependencies work properly.

Do you have any suggestions what I might be doing wrong?

**Comment by massa84** [comment]
I've just tried the tag on the demo page and everything seems to work : http://mailonline.github.io/videojs-vast-vpaid/

**Comment by MichelVenatus** [comment]
@massa84 Not helpful, I have the same problem as @yairneumann11 with a Liverail tag, it works fine on the demo page, on my own demo page, but if I update the adUrl in the demo file it does not work at all, I cannot see any outgoing request to it.

As a side note it's extremely annoying to have to use gulp to run the demo.

**Comment by Fetz** [comment]
@yairneumann11 
Are you using [videojs-vast-vpaid plugin](https://github.com/MailOnline/videojs-vast-vpaid)? or the [VPAIDFLASHClient](https://github.com/MailOnline/VPAIDFLASHClient)?

If the VPAIDFlashClient, is a bit low level to use directly, the demo used in the VPAIDFlashClient is only a fast prototype to test the VPAIDFlashClient without depending on the plugin, and to allow other projects to use it

**Comment by Fetz** [comment]
closing the issue, when more details are provided please reopen the issue

**Comment by sportexholdings** [comment]
Hi!, If I am using  videojs-vast-vpaid plugin.How i get it work
